### ISSUE TITLE
Many Errors on the latest Addon pack

### ISSUE THREAD

**Issue by sasadubi** [Schaka/WotLK-AddOns_TBC#1]
Hey Schaka,

I'm heavily using your ArenaLive, and after using the latest version you published on Warmane thread [2 weeks ago], I'm here to report some of the bugs. Sometimes errors accumulate to up to 600-700.
Posting few screenshots here:
![bug4](https://github.com/user-attachments/assets/4eba3fee-2d2a-476e-9bfb-cc1121ac5974)
![bug2](https://github.com/user-attachments/assets/388d0614-1fb6-461d-9cab-3fc9e99434cd)
![bug6](https://github.com/user-attac
![bug8](https://github.com/user-attachments/assets/719d879f-c35e-4563-9376-ef3129c6e6ed)
![bug7](https://github.com/user-attachments/assets/dd277927-67d3-4f76-b416-1616dbde0080)
![bug1](https://github.com/user-attachments/assets/72d6885a-f6b8-4303-ac3e-0904e8d69410)
![bug10](https://github.com/user-attachments/assets/337a849c-165e-4158-bec7-b5d508b1a21b)
![bug3](https://github.com/user-attachments/assets/c5a9256a-1cf7-4afa-8499-b1e04e857111)
![bug9](https://github.com/user-attachments/assets/26a30d80-00cc-4364-b4e2-4733cc65340e)
hments/assets/b3710405-3a55-44f3-8ca1-518945437113)
![bug5](https://github.com/user-attachments/assets/ed221b8f-bb49-48b4-b39a-468169f92451)

Take a look when you have time!

Thankfully in advance

**Comment by Evolvee** [comment]
you have outdated classicapi addon

the taint was fixed a month ago

**Comment by Schaka** [comment]
https://gitlab.com/Tsoukie/classicapi

Grab from here. The one in my repo is up to date, btw. At least the latest official release (1.1.64) that has the taint fixed.

**Comment by sasadubi** [comment]
Okay, thanks!
